name = "App-week"
readme_from = "script/week"
badges = ['github-actions/test', 'metacpan']
authority="cpan:UTASHIRO"

module_maker="ModuleBuildTiny"

[unsupported]
os = [
    "MSWin32",
]

[FileGatherer]
exclude_match=['^docs/.*']
